### ISSUE TITLE
Zip archive doesn't extract properly?

### ISSUE THREAD

**Issue by bknowles** [stisti/jenkins-app#14] opened 2012-07-12 19:03 UTC
Either the instructions are wrong, or the zip archive no longer matches the instructions.  When I download the current zip archive, I get the file named "stisti-jenkins-app-307d0fe.zip" downloaded to my machine.  When I extract this archive, it creates the folder named "stisti-jenkins-app-307d0fe".  This folder contains the following files:

```
$ ls -la
total 104
drwxr-xr-x@ 11 brad  staff   374 Jul 12 11:52 .
drwx------+ 18 brad  staff   612 Jul 12 11:50 ..
-rw-r--r--@  1 brad  staff  6148 Jul 12 11:52 .DS_Store
-rwxr-xr-x@  1 brad  staff   155 Jul  8 14:58 .gitignore
-rwxr-xr-x@  1 brad  staff  1367 Jul  8 14:58 Info.plist
drwxr-xr-x@  3 brad  staff   102 Jul  8 14:58 Jenkins.app
-rwxr-xr-x@  1 brad  staff   150 Jul  8 14:58 Makefile
-rwxr-xr-x@  1 brad  staff  4775 Jul  8 14:58 README.rst
-rwxr-xr-x@  1 brad  staff  1963 Jul  8 14:58 build.xml
-rwxr-xr-x@  1 brad  staff  9107 Jul  8 14:58 main.applescript
-rwxr-xr-x@  1 brad  staff  5606 Jul  8 14:58 utils.applescript
```

The "Jenkins.app" contained within this folder is not executable.  When I click on it or otherwise try to open it, I get the error message:

```
You can't open the application Jenkins
because it may be damaged or
incomplete.
```

Looking inside the package contents for Jenkins.app, I don't see anything that is obviously amiss:

```
$ ls -laR
total 0
drwxr-xr-x@  3 brad  staff  102 Jul  8 14:58 .
drwxr-xr-x@ 11 brad  staff  374 Jul 12 11:52 ..
drwxr-xr-x@  5 brad  staff  170 Jul  8 14:58 Contents

./Contents:
total 8
drwxr-xr-x@ 5 brad  staff  170 Jul  8 14:58 .
drwxr-xr-x@ 3 brad  staff  102 Jul  8 14:58 ..
drwxr-xr-x@ 3 brad  staff  102 Jul  8 14:58 MacOS
-rwxr-xr-x@ 1 brad  staff    8 Jul  8 14:58 PkgInfo
drwxr-xr-x@ 7 brad  staff  238 Jul  8 14:58 Resources

./Contents/MacOS:
total 112
drwxr-xr-x@ 3 brad  staff    102 Jul  8 14:58 .
drwxr-xr-x@ 5 brad  staff    170 Jul  8 14:58 ..
-rwxr-xr-x@ 1 brad  staff  55856 Jul  8 14:58 applet

./Contents/Resources:
total 520
drwxr-xr-x@ 7 brad  staff     238 Jul  8 14:58 .
drwxr-xr-x@ 5 brad  staff     170 Jul  8 14:58 ..
-rwxr-xr-x@ 1 brad  staff  214234 Jul  8 14:58 Jenkins.icns
-rwxr-xr-x@ 1 brad  staff   40291 Jul  8 14:58 applet.icns
-rwxr-xr-x@ 1 brad  staff     388 Jul  8 14:58 applet.rsrc
drwxr-xr-x@ 3 brad  staff     102 Jul  8 14:58 description.rtfd
-rwxr-xr-x@ 1 brad  staff     273 Jul  8 14:58 wait_for_jenkins.sh

./Contents/Resources/description.rtfd:
total 8
drwxr-xr-x@ 3 brad  staff  102 Jul  8 14:58 .
drwxr-xr-x@ 7 brad  staff  238 Jul  8 14:58 ..
-rwxr-xr-x@ 1 brad  staff  102 Jul  8 14:58 TXT.rtf
```

I'm confused.  Did I do something stupid?  Did I miss something?  Is there any additional information or documentation I can supply that might be useful?  Thanks!

**Comment by stisti** [comment] 2012-07-12 22:06
It seems you me you have downloaded the source for Jenkins.app. If you want to build it from the source, you need to run the command "ant" in the top of the source tree. By the way, instead of downloading the source as a zip archive, it usually makes more sense to clone the git repo, as it makes it easier to keep your copy of the sources up to date and contribute changes back to me.

If you weren't interested in the sources, then you can download ready-to-run packages under the Downloads tab (https://github.com/stisti/jenkins-app/downloads).

Oh, now I see there's a "Download as zip" button on the github downloads page! Don't click that. Scroll down where it says "Download Packages".

-- Sami

Brad Knowles kirjoitti 12.7.2012 kello 22.03:

**Comment by stisti** [comment] 2012-07-12 22:11
No problem found. I re-verified Jenkins_34.zip package contains a working application. I suspect the confusion was caused by Github having a source zip download button on the Downloads page. Closing the case.

**Closed as completed** 2012-07-12 22:12 UTC

**Comment by bknowles** [comment] 2012-07-12 22:49
D'oh!

Thanks!
